//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSG_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Echipe_TSG
    {
        public int ID_Echipa { get; set; }
        public int ID_TeamLeader { get; set; }

        public override string ToString()
        {
            return "Echipa: " + this.ID_Echipa + " " + this.ID_TeamLeader;
        }
    }
}
